name: "Image Build and Push"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  packages: write

  # This is used to complete the identity challenge with sigstore/fulcio.
  id-token: write

jobs:
  build-push:
    uses: darbiadev/.github/.github/workflows/docker-build-push.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
